name: pysyncon

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        buildplat: [ubuntu-20.04, windows-2019]
        python: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.buildplat }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-dev.txt
    - name: Lint
      run: |
        black --check .
    - name: Run tests
      run: |
        python -m unittest discover -s tests
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
          python -m pip install codecov
      - name: Run tests and collect coverage
        run: coverage run -m unittest discover -s tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
